=== 06wj/glTF/specification/glTF.schema.json
{
    "$schema" : "http://json-schema.org/draft-03/schema",
    "title" : "glTF",
    "type" : "object",
    "description" : "Top-level glTF property.",
    "properties" : {
        "asset" : {
            "$ref" : "asset.schema.json"
        },
        "accessors" : {
            "properties" : {
            },
            "additionalProperties" : {
                "$ref" : "accessor.schema.json"
            }
        },
        "animations" : {
            "properties" : {
            },
            "additionalProperties" : {
                "$ref" : "animation.schema.json"
            }
        },
        "buffers" : {
            "properties" : {
            },
            "additionalProperties" : {
                "$ref" : "buffer.schema.json"
            }
        },
        "bufferViews" : {
            "properties" : {
            },
            "additionalProperties" : {
                "$ref" : "bufferView.schema.json"
            }
        },
        "cameras" : {
            "properties" : {
            },
            "additionalProperties" : {
                "$ref" : "camera.schema.json"
            }
        },
        "extensions" : {
            "type" : "array",
            "description" : "Names of extensions used by this model.  WebGL: see getSupportedExtensions() and getExtension().",
            "items" : {
                "type" : "string"
            },
            "uniqueItems" : true
        },
        "images" : {
            "properties" : {
            },
            "additionalProperties" : {
                "$ref" : "image.schema.json"
            }
        },
        "lights" : {
            "properties" : {
            },
            "additionalProperties" : {
                "$ref" : "light.schema.json"
            }
        },
        "materials" : {
            "properties" : {
            },
            "additionalProperties" : {
                "$ref" : "material.schema.json"
            }
        },
        "meshes" : {
            "properties" : {
            },
            "additionalProperties" : {
                "$ref" : "mesh.schema.json"
            }
        },
        "nodes" : {
            "properties" : {
            },
            "additionalProperties" : {
                "$ref" : "node.schema.json"
            }
        },
        "programs" : {
            "properties" : {
            },
            "additionalProperties" : {
                "$ref" : "program.schema.json"
            }
        },
        "samplers" : {
            "properties" : {
            },
            "additionalProperties" : {
                "$ref" : "sampler.schema.json"
            }
        },
        "scene" : {
            "type" : "string",
            "description" : "The id (JSON property name) of the default scene."
        },
        "scenes" : {
            "properties" : {
            },
            "additionalProperties" : {
                "$ref" : "scene.schema.json"
            }
        },
        "shaders" : {
            "properties" : {
            },
            "additionalProperties" : {
                "$ref" : "shader.schema.json"
            }
        },
        "skins" : {
            "properties" : {
            },
            "additionalProperties" : {
                "$ref" : "skin.schema.json"
            }
        },
        "techniques" : {
            "properties" : {
            },
            "additionalProperties" : {
                "$ref" : "technique.schema.json"
            }
        },
        "profile" : {
            "type" : "string",
            "description" : "Specifies the target rendering API and version, e.g., WebGL 1.0.2.",
            "default" : "WebGL 1.0.2"
        },        
        "version" : {
            "type" : "string",
            "description" : "The glTF version.",
            "default" : "1.0"
        },
        "textures" : {
            "properties" : {
            },
            "additionalProperties" : {
                "$ref" : "texture.schema.json"
            }
        },
        "extras" : {
            "type" : "any",
            "description" : "Optional application-specific data."
        }
    },
    "additionalProperties" : false
}

=== 06wj/glTF/webgl/apps/viewer/model/wine/wine.json
{
    "buffers": {
        "wine.bin": {
            "byteLength": 329004,
            "path": "wine.bin",
            "type": "ArrayBuffer"
        }
    },
    "cameras": {
        "camera_0": {
            "projection": "perspective",
            "type": "camera",
            "yfov": 45,
            "zfar": 3162.76,
            "znear": 12.651
        }
    },
    "materials": {
        "material.0": {
            "inputs": {
                "diffuseColor": [
                    1,
                    1,
                    1
                ]
            },
            "name": "",
            "technique": "lambert0",
            "type": "material"
        },
        "material.1": {
            "inputs": {
                "diffuseColor": [
                    1,
                    1,
                    1
                ]
            },
            "name": "",
            "technique": "lambert0",
            "type": "material"
        },
        "material.2": {
            "inputs": {
                "diffuseTexture": "Wood_Cherry_Original_.jpg"
            },
            "name": "Wood_Cherry_Original_",
            "technique": "lambert1",
            "type": "material"
        },
        "material.3": {
            "inputs": {
                "diffuseColor": [
                    0.564706,
                    0.972549,
                    0.835294
                ],
                "transparency": 0.14902
            },
            "name": "material_5",
            "technique": "lambert2",
            "type": "material"
        },
        "material.4": {
            "inputs": {
                "diffuseTexture": "_2004_old_vine_zinfandel_btl_xlg.jpg"
            },
            "name": "_2004_old_vine_zinfandel_btl_xlg",
            "technique": "lambert1",
            "type": "material"
        },
        "material.5": {
            "inputs": {
                "diffuseColor": [
                    1,
                    1,
                    1
                ]
            },
            "name": "material",
            "technique": "lambert0",
            "type": "material"
        },
        "material.6": {
            "inputs": {
                "diffuseTexture": "artezin_bottle.jpg"
            },
            "name": "artezin_bottle",
            "technique": "lambert1",
            "type": "material"
        }
    },
    "meshes": {
        "geometry16": {
            "accessor.12": {
                "buffer": "wine.bin",
                "byteOffset": 0,
                "byteStride": 8,
                "count": 96,
                "elementType": "Float32",
                "elementsPerValue": 2,
                "type": "accessor"
            },
            "accessor.14": {
                "buffer": "wine.bin",
                "byteOffset": 336,
                "byteStride": 12,
                "count": 96,
                "elementType": "Float32",
                "elementsPerValue": 3,
                "max": [
                    2,
                    21,
                    38
                ],
                "min": [
                    0,
                    0,
                    5.5
                ],
                "type": "accessor"
            },
            "accessor.15": {
                "buffer": "wine.bin",
                "byteOffset": 1488,
                "byteStride": 12,
                "count": 96,
                "elementType": "Float32",
                "elementsPerValue": 3,
                "max": [
                    1,
                    1,
                    1
                ],
                "min": [
                    -1,
                    -1,
                    -1
                ],
                "type": "accessor"
            },
            "accessor.16": {
                "buffer": "wine.bin",
                "byteOffset": 2640,
                "byteStride": 8,
                "count": 96,
                "elementType": "Float32",
                "elementsPerValue": 2,
                "max": [
                    4.15963,
                    1.08885
                ],
                "min": [
                    -1.14777,
                    -0.113737
                ],
                "type": "accessor"
            },
            "name": "geometry16",
            "primitives": [
                {
                    "indices": {
                        "buffer": "wine.bin",
                        "byteOffset": 0,
                        "length": 168,
                        "type": "Uint16Array"
                    },
                    "material": "material.2",
                    "primitive": "TRIANGLES",
                    "type": "primitive",
                    "vertexAttributes": [
                        {
                            "accessor": "accessor.14",
                            "semantic": "VERTEX"
                        },
                        {
                            "accessor": "accessor.15",
                            "semantic": "NORMAL"
                        },
                        {
                            "accessor": "accessor.16",
                            "semantic": "TEXCOORD",
                            "set": "1"
                        }
                    ]
                }
            ],
            "type": "mesh"
        },
        "geometry24": {
            "accessor.22": {
                "buffer": "wine.bin",
                "byteOffset": 7296,
                "byteStride": 12,
                "count": 720,
                "elementType": "Float32",
                "elementsPerValue": 3,
                "max": [
                    16.8,
                    19.5,
                    0.75
                ],
                "min": [
                    1.4,
                    -0,
                    0
                ],
                "type": "accessor"
            },
            "accessor.23": {
                "buffer": "wine.bin",
                "byteOffset": 15936,
                "byteStride": 12,
                "count": 720,
                "elementType": "Float32",
                "elementsPerValue": 3,
                "max": [
                    1,
                    1,
                    1
                ],
                "min": [
                    -1,
                    -1,
                    -1
                ],
                "type": "accessor"
            },
            "name": "geometry24",
            "primitives": [
                {
                    "indices": {
                        "buffer": "wine.bin",
                        "byteOffset": 3408,
                        "length": 1944,
                        "type": "Uint16Array"
                    },
                    "material": "material.3",
                    "primitive": "TRIANGLES",
                    "type": "primitive",
                    "vertexAttributes": [
                        {
                            "accessor": "accessor.22",
                            "semantic": "VERTEX"
                        },
                        {
                            "accessor": "accessor.23",
                            "semantic": "NORMAL"
                        }
                    ]
                }
            ],
            "type": "mesh"
        },
        "geometry29": {
            "accessor.29": {
                "buffer": "wine.bin",
                "byteOffset": 28464,
                "byteStride": 12,
                "count": 720,
                "elementType": "Float32",
                "elementsPerValue": 3,
                "max": [
                    16.8,
                    19.5,
                    0.75
                ],
                "min": [
                    1.4,
                    -0,
                    0
                ],
                "type": "accessor"
            },
            "accessor.30": {
                "buffer": "wine.bin",
                "byteOffset": 37104,
                "byteStride": 12,
                "count": 720,
                "elementType": "Float32",
                "elementsPerValue": 3,
                "max": [
                    1,
                    1,
                    1
                ],
                "min": [
                    -1,
                    -1,
                    -1
                ],
                "type": "accessor"
            },
            "name": "geometry29",
            "primitives": [
                {
                    "indices": {
                        "buffer": "wine.bin",
                        "byteOffset": 24576,
                        "length": 1944,
                        "type": "Uint16Array"
                    },
                    "material": "material.3",
                    "primitive": "TRIANGLES",
                    "type": "primitive",
                    "vertexAttributes": [
                        {
                            "accessor": "accessor.29",
                            "semantic": "VERTEX"
                        },
                        {
                            "accessor": "accessor.30",
                            "semantic": "NORMAL"
                        }
                    ]
                }
            ],
            "type": "mesh"
        },
        "geometry35": {
            "accessor.36": {
                "buffer": "wine.bin",
                "byteOffset": 0,
                "byteStride": 8,
                "count": 30,
                "elementType": "Float32",
                "elementsPerValue": 2,
                "type": "accessor"
            },
            "accessor.38": {
                "buffer": "wine.bin",
                "byteOffset": 45840,
                "byteStride": 12,
                "count": 30,
                "elementType": "Float32",
                "elementsPerValue": 3,
                "max": [
                    0.5,
                    21,
                    46.6166
                ],
