=== 06wj/glTF/schema/material.schema.json
{
    "$schema" : "http://json-schema.org/draft-03/schema",
    "title" : "material",
    "type" : "object",
    "description" : "TODO",
    "properties": {    
        "name" : {
            "type" : "string",
            "description" : "The externally-referenceable globally-unique name of this node."
        },
        "parameters" : {
	        "$ref" : "parameters.schema.json"
        },
        "technique" : {
            "type" : "string",
            "description" : "The name of the default technique referenced by this material.",
            "required" : true
        },
        "techniques" : {
            "description" : "The techniques available to this material.",
            "properties" : {
            },
            "additionalProperties" : {
                "$ref" : "technique.schema.json"
            },
            "required" : true
        },
        "extra" : {
            "type" : "any",
            "description" : "Optional application-specific data."
        }
    },
    "additionalProperties" : false
}

=== 06wj/glTF/specification/examples/material/material.json
{
    "name" : "application-visible globally-unique name",
    "parameters" : {
    },
    "technique" : "exampleTechnique",
    "techniques" : {
		"exampleTechnique" : {
		    "pass" : {
			    "program" : {
					"attributes" : [{
				    	"symbol" : "position",
				    	"type" : "vec3"
					}],
					"fragmentShader" : "fragmentShader_id",
					"vertexShader" : "vertexShader_id"
			    }
			}
		}
    },
    "extra" : {
       "Application specific" : "The extra object can contain any properties."
    }     
}
